linewalks/lwds

src/components/Button/Button.md, src/components/Button/Button.scss, src/components/Button/Button.test.js, src/components/Button/Button.tsx, src/components/Icon/SVGIcon.tsx
* Icon 사용하게 수정
* Vertical 정렬 가운데 딱 안맞던 것 수정
* className에 size, variant 관련 카테고리? 정보 추가
* button-lg --> buttno-size-lg
* variant, color 분리
* 분리 후, scss 리팩토링
close #47
=> Issue47.button review

src/components/Size/Size.md, src/components/Spacing/Spacing.md, styleguide.config.js
- lwds 스타일 가이드에서 size와 spacing 에 대한 semantics 을 쉽게 파악하기 위한 md 파일을 구성하였습니다.
- 필요성이 높아질 경우 `SizeTable` 과 `SpacingTable` 을 구성해서 속성값을 쉽게 파악할 수 있도록 구성합니다.
=> Issue81.size spacing docs

package.json, styleguide.config.js, yarn.lock
- styleguide.config.js 에서 `withCustomConfig`를 활용해서 tsconfig.json 을 활용할 때 include, exclude 속성을 활용하지 못하는 문제 존재
- styleguide.config.js 의 `withCustomConfig` 설정을 구체화
```js
// before
propsParser: require('react-docgen-typescript').withCustomConfig(
'./tsconfig.json',
).parse,
//after
propsParser: (filePath, source, resolver, handlers) => {
const { ext } = path.parse(filePath)
return ext === '.tsx'
? require('react-docgen-typescript')
.withCustomConfig(`${process.cwd()}/tsconfig.json`)
.parse(filePath, source, resolver, handlers)
: require('react-docgen').parse(source, resolver, handlers)
},
```
=> tsconfig.json 을 활용한 styleguide 빌드 시 모듈 접근 불가

src/components/Color/Colors.md, src/components/Color/Colors.tsx, styleguide.config.js
- LWDS 에 구성된 Color Semantic을 쉽게 파악할 수 있도록 color styleguide 문서를 구성하였습니다
=> LWDS Color palette styleguide 문서 구성 

src/components/Font/Font.md, styleguide.config.js
- font size 사용방법에 대한 styleguide 문서를 추가했습니다.
- 현 방식은 기존 MDWalks-UI 의 사용방법을 그대로 적용하고 있고 추후 공식 시안이 나오면 그에 맞춰 수정될 예정입니다.
=> font size styleguide 문서 추가

src/components/Icon/Icons/Specific/ConceptSetIcon.tsx, src/components/Icon/Icons/Specific/ConceptSetSelectedIcon.tsx
- 아이콘 컴포넌트에서 kebab case 를 사용하는 props들에 대해 camel case 로 수정하였습니다.
=> [icons] kebab case props 변환

src/components/Button/Button.scss
- margin default 제거
- tertiary border 추가
- ghost important disabled text color
=> [Button] component 디자인 관련 에러 수정

src/components/Icon/Icons/Specific/ConceptSetIcon.tsx
- ConceptSetIcon 에서 발생한 일부 깨짐 현상을 해결하였습니다.
=> chore: ConceptSetIcon 깨짐 문제 해결

src/assets/styles/color/colors.js, src/assets/styles/color/semantics.js, src/assets/styles/defaultStyle.js, src/assets/styles/typography/typography.scss, src/components/Button/Button.scss, src/components/Spacing/Spacing.md, tailwind.config.js
- 다음 [QA 문서](https://linewalks.atlassian.net/wiki/spaces/LWDS/pages/309395483/QA+220323+LWDS+QA)를 참고하여 Color, Button, Typo 스타일을 수정하였습니다.
- icon_04 내부 값 변경, highlight color opacity 추가
- tertiary button : 1px border
- typo: body_medium line-height 수정
=> [BUG] LWDS QA 항목 수정 (Color, Button, Typo)

styleguide.config.js
- Icon 의 카테고리를 Component에서 Foundation 으로 수정합니다.
=> [Icon] Icon 카테고리 변경

src/components/Button/Button.scss
=> fix: ghost important color

src/components/Dropdown/Dropdown.test.js, src/components/Dropdown/Dropdown.tsx
- Dropdown 컴포넌트에 대한 테스트 코드를 추가하였습니다.
=> [Dropdown] Dropdown 컴포넌트 테스트 코드

src/components/Dropdown/Dropdown.scss
- hr 태그에 대한 border-width 스타일을 추가하였습니다.
=> [Dropdown] Dropdown divider style 수정

src/components/ProgressBar/ProgressBar.md, src/components/ProgressBar/ProgressBar.scss, src/components/ProgressBar/ProgressBar.test.js, src/components/ProgressBar/ProgressBar.tsx, styleguide.config.js
*ProgressBar 구현*
- 기반은 MDwalks-UI
- props은 아래와 같음
```
placement?: 'top' | 'right' | 'bottom' | 'left' // 위치
value: string | number // 입력 값
size?: 'sm' | 'md' // label 의 사이즈
width?: string | number // 컴포넌트의 길이
thickness?: string | number // 프로그래스바의 두께
strokeColor?: string // 프로그래스바의 색상
max?: string | number // 최대값 (준 필수 값)
isInfinite?: boolean // 프로그래스 무한 반복 여부
children?: React.ReactNode 
```
=> ProgressBar 구현

less/variables.less, package.json, scss/variables.scss
- css-in-js 환경이 아닌 sass, less 환경에서도 semantics 를 import 할 수 있는 variables 를 구성하였습니다.
=> [Style] sass, less 환경 semantics variables 구성

src/components/CheckBox/CheckBox.md, src/components/CheckBox/CheckBox.scss, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/CheckBoxSet.tsx, styleguide.config.js
https://www.figma.com/file/kgd55imcvmKYSQJQnNky2a/%5BMaster%5D-LWDS_1.3.0?node-id=0%3A2997
- Checkbox component prototype
- 이전 MDwalks-UI의 checkbox의 경우 input checkbox type이 아닌 div로 구현된 관계로 웹브라우저 input tag의 네이티브 기능들을 수행할 수 없었음
- input tag를 활용함으로 check state의 주입이 아닌 onChange 핸들러를 통해 전달 받는 방식
- Set의 경우 자손들의 상태에 따라 모체의 상태가 바뀌어야 하기에 init 기준으로 관리
- Label 및 Set의 자손들이 모체(input)과 짝이 되어 모체의 상태를 알아야 하는 관계로 children 활용하지 않았는데, 혹 우회적인 아이디어가 있으면 리뷰 부탁드립니다.
-  `& + &` 등 기획에서의 spacing 요구가 있어 반영은 하였지만, 라이브러리 단에서는 제거를 하는 것이 좋지 않을까 생각이 듬
=> [Checkbox] Checkbox prototype

src/components/Tabs/Tabs.md, src/components/Tabs/Tabs.scss
fix: tabs scroll button fix css
- closes #188
=> fix: tabs scroll button fix css

src/components/Tabs/Tabs.scss
=> fix: Tabs hover css

src/index.ts
- 컴포넌트 모듈을 export 하지 않은 문제를 해결하였습니다.
=> [BUG] 컴포넌트 모듈 export 문제 해결

src/components/Button/Button.tsx
- Button에 className을 설정할 수 있는 기능을 추가하였습니다.
- leftIcon, rightIcon 에 className 을 설정할 수 있는 기능을 추가하였습니다.
=> [Button] className 설정 기능 추가

src/components/Dropdown/Dropdown.md, src/components/Dropdown/Dropdown.scss, src/components/Dropdown/Dropdown.tsx
- Dropdown Overflow 에 대해 z-index 쌓음 규칙을 회피하기 위해 list에 Portal을 적용하였습니다.
- Portal 을 통한 global position 을 재계산하였습니다.
=> [Dropdown] Overflow 스타일 적용

src/components/Button/Button.tsx
- Button 컴포넌트의 props 타입을 optional 하게 변경하였습니다.
=> [Button] 불필요한 props 의 Type 을 optional 로 지정

src/components/Dropdown/Dropdown.tsx
- 불필요한 Dropdown click 이벤트 전파를 차단하였습니다.
=> [Dropdown] Dropdown click 이벤트 전파 차단

src/components/Button/Button.scss
=> fix: ghost button - transparent 적용

src/components/Button/Button.tsx
- 불필요한 버튼 컴포넌트의 type을 변경하였습니다.
=> [Button] 버튼 컴포넌트 필수 type 변경 

styleguide.config.js
- Webpack 설정 수정에 따라 발생하는 스타일 가이드 빌드 에러를 수정하였습니다.
=> [Config] 스타일 가이드 빌드 에러 수정

package.json, rollup.config.js, styleguide.config.js, webpack.config.js
- 코드를 번들링할 때 사용하는 CSS 도 같이 export 할 수 있도록 수정하였습니다.
=> [Config] 번들 과정 중 CSS 파일 export

src/components/Tooltip/Tooltip.md, src/components/Tooltip/Tooltip.scss, src/components/Tooltip/Tooltip.tsx
=> [Tooltip] feat: multiline

package.json, src/components/Icon/Icons/index.ts, webpack.config.js, yarn.lock
feat: apply add check icons
- 기존에 누락되어있던 아이콘 추가
- package.json react-scripts, styleguidist 버전 업
=> feat: apply add check icons

package.json
improvement: package json node version
- package.json export typo
=> improvement: package json node version

package.json, src/components/Tooltip/Tooltip.tsx, yarn.lock
- Tooltip 컴포넌트 내 children을 복사하던 과정 중 children의 className이 누락되는 문제를 수정하였습니다.
- 기존 Tooltip props 로 전달받는 className은 Tooltip 메세지 컴포넌트를 가리키도록 수정하였습니다.
=> [BUG] Tooltip children 컴포넌트 className 스킵 문제 수정

src/components/Toast/Toast.tsx, src/index.ts
chore: remove unused toast component
=> chore: remove unused toast component

src/index.ts
fix: build error
toast build error
=> fix: build error

package.json, yarn.lock
pack: integrate node sass and sass
=> pack: integrate node sass and sass

.babelrc, package.json, rollup.config.js, src/components/Tooltip/Tooltip.md, src/components/Tooltip/Tooltip.tsx, styleguide.config.js, webpack.config.js
fix: tooltip placement
- closes #256 
- tooltip 위치 조정 수정
=> fix: tooltip placement

README.md, package.json
=> chore: contributors
